# ZMK Split Central (동글 수신기) 역할 설정
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=y

# USB HID 1000Hz (1ms) 폴링레이트 설정
CONFIG_USB_HID_POLL_INTERVAL=1

# ZMK Studio (웹 실시간 키 매핑) 활성화
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 수신기 성능 극대화
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
